on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      matrix:
        side: [left, right]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Sofle ${{ matrix.side }})
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_${{ matrix.side }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Sofle ${{ matrix.side }} Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 sofle_${{ matrix.side }}_nice_nano_v2.uf2

      - name: Archive (Sofle ${{ matrix.side }})
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.side }}-${{ github.run_id }}
          path: sofle_${{ matrix.side }}_nice_nano_v2.uf2
